export const GETREALNAME: string = 'getRealname'
export const SETREALNAME: string = 'setRealname'
export const SETFUN: string = 'setfun'
export const SETAREA: string = 'setarea'
export const SETADDRESSFUN: string = 'setAddressFun'