export const GETAREAINFO: string = 'getareainfo'
export const SETAREAINFO: string = 'setareainfo'
export const SETAREA: string = 'setarea'
export const GETAREA: string = 'getarea'
export const SETPOSITIONSTATUS: string = 'setpositionstatus'
export const SETTOKEN: string ='settoken'
export const GETTOKEN: string ='gettoken'
export const SETPHONE: string = 'setphone'