/*
 * @Author: zyb
 * @Date: 2020-11-03 18:49:37
 * @LastEditors: zyb
 * @LastEditTime: 2020-11-04 10:39:51
 * @Description: 
 */
// 基础信息默认参数
export const INFODATA_DATA =  {
  ad_code: 0,
  address: '',
  admin_last_edit_time: '',
  admin_user_id: '',
  authentication: '',
  birthday: '',
  certificate_show: 0,
  check: '',
  city: '未填写',
  collect_num: '',
  complain_num: '',
  country: '',
  current_admin: '',
  distance: '',
  experience: '',
  extens: '',
  gender: '',
  headerimg: '',
  hometown: '',
  id: '',
  img: '',
  introduce: '未填写',
  ip_address: '',
  is_end: '',
  is_introduces: '',
  location: '',
  miniInfoOccupations: [],
  nation: '',
  nation_id: '',
  note: '',
  number_people: '',
  occupations: [],
  occupations_id: '',
  prof_degree: '',
  progress: '0',
  province: '',
  provinces: '',
  ranking: '',
  refresh_time: '',
  sort_flag: '',
  source: '',
  tags: [],
  tel: '未填写',
  time: '',
  type: '',
  update_time: '',
  user_id: '',
  user_uuid: '',
  username: '',
  uuid: '',
  view_num: '',
  zan_num: '',
  age:'未填写',
}

// 人员信息
export const INTRODUCERS_DATA = {
  check: '',
  experience: '',
  experience_str: '',
  hometown: '未填写',
  hometown_id: '',
  number_people: '',
  prof_degree: '',
  prof_degree_str: '',
  tag_id: '',
  tags: [],
  type: '',
  type_str: '',
}