import { Areas } from 'src/config/store'

const AREAS: ParentItems[] = [{
  "id": "1",
  "pid": "0",
  "name": "全国",
  "ad_name": "中国",
  "letter": "quanguo",
  "has_children": 0,
  "children": []
}, {
  "id": "2",
  "pid": "1",
  "name": "北京",
  "ad_name": "北京市",
  "letter": "beijing",
  "has_children": 0,
  "children": []
}, {
  "id": "3",
  "pid": "1",
  "name": "安徽",
  "ad_name": "安徽省",
  "letter": "anhui",
  "has_children": 1,
  "children": [{
    "id": "3",
    "pid": "1",
    "name": "安徽",
    "ad_name": "安徽省",
    "letter": "anhui"
  }, {
    "id": "36",
    "pid": "3",
    "name": "安庆",
    "ad_name": "安庆市",
    "letter": "anqing"
  }, {
    "id": "37",
    "pid": "3",
    "name": "蚌埠",
    "ad_name": "蚌埠市",
    "letter": "bengbu"
  }, {
    "id": "39",
    "pid": "3",
    "name": "池州",
    "ad_name": "池州市",
    "letter": "chizhou"
  }, {
    "id": "40",
    "pid": "3",
    "name": "滁州",
    "ad_name": "滁州市",
    "letter": "chuzhou"
  }, {
    "id": "41",
    "pid": "3",
    "name": "阜阳",
    "ad_name": "阜阳市",
    "letter": "fuyang"
  }, {
    "id": "42",
    "pid": "3",
    "name": "淮北",
    "ad_name": "淮北市",
    "letter": "huaibei"
  }, {
    "id": "43",
    "pid": "3",
    "name": "淮南",
    "ad_name": "淮南市",
    "letter": "huainan"
  }, {
    "id": "44",
    "pid": "3",
    "name": "黄山",
    "ad_name": "黄山市",
    "letter": "huangshan"
  }, {
    "id": "45",
    "pid": "3",
    "name": "六安",
    "ad_name": "六安市",
    "letter": "liuan"
  }, {
    "id": "46",
    "pid": "3",
    "name": "马鞍山",
    "ad_name": "马鞍山市",
    "letter": "maanshan"
  }, {
    "id": "47",
    "pid": "3",
    "name": "宿州",
    "ad_name": "宿州市",
    "letter": "anhuisuzhou"
  }, {
    "id": "48",
    "pid": "3",
    "name": "铜陵",
    "ad_name": "铜陵市",
    "letter": "tongling"
  }, {
    "id": "49",
    "pid": "3",
    "name": "芜湖",
    "ad_name": "芜湖市",
    "letter": "wuhu"
  }, {
    "id": "50",
    "pid": "3",
    "name": "宣城",
    "ad_name": "宣城市",
    "letter": "xuancheng"
  }, {
    "id": "51",
    "pid": "3",
    "name": "亳州",
    "ad_name": "亳州市",
    "letter": "bozhou"
  }, {
    "id": "3401",
    "pid": "3",
    "name": "合肥",
    "ad_name": "合肥市",
    "letter": "hefei"
  }]
}, {
  "id": "4",
  "pid": "1",
  "name": "福建",
  "ad_name": "福建省",
  "letter": "fujian",
  "has_children": 1,
  "children": [{
    "id": "4",
    "pid": "1",
    "name": "福建",
    "ad_name": "福建省",
    "letter": "fujian"
  }, {
    "id": "53",
    "pid": "4",
    "name": "福州",
    "ad_name": "福州市",
    "letter": "fuzhou"
  }, {
    "id": "54",
    "pid": "4",
    "name": "龙岩",
    "ad_name": "龙岩市",
    "letter": "longyan"
  }, {
    "id": "55",
    "pid": "4",
    "name": "南平",
    "ad_name": "南平市",
    "letter": "nanping"
  }, {
    "id": "56",
    "pid": "4",
    "name": "宁德",
    "ad_name": "宁德市",
    "letter": "ningde"
  }, {
    "id": "57",
    "pid": "4",
    "name": "莆田",
    "ad_name": "莆田市",
    "letter": "putian"
  }, {
    "id": "58",
    "pid": "4",
    "name": "泉州",
    "ad_name": "泉州市",
    "letter": "quanzhou"
  }, {
    "id": "59",
    "pid": "4",
    "name": "三明",
    "ad_name": "三明市",
    "letter": "sanming"
  }, {
    "id": "60",
    "pid": "4",
    "name": "厦门",
    "ad_name": "厦门市",
    "letter": "xiamen"
  }, {
    "id": "61",
    "pid": "4",
    "name": "漳州",
    "ad_name": "漳州市",
    "letter": "zhangzhou"
  }]
}, {
  "id": "5",
  "pid": "1",
  "name": "甘肃",
  "ad_name": "甘肃省",
  "letter": "gansu",
  "has_children": 1,
  "children": [{
    "id": "5",
    "pid": "1",
    "name": "甘肃",
    "ad_name": "甘肃省",
    "letter": "gansu"
  }, {
    "id": "62",
    "pid": "5",
    "name": "兰州",
    "ad_name": "兰州市",
    "letter": "lanzhou"
  }, {
    "id": "63",
    "pid": "5",
    "name": "白银",
    "ad_name": "白银市",
    "letter": "baiyin"
  }, {
    "id": "64",
    "pid": "5",
    "name": "定西",
    "ad_name": "定西市",
    "letter": "dingxi"
  }, {
    "id": "65",
    "pid": "5",
    "name": "甘南",
    "ad_name": "甘南藏族自治州",
    "letter": "gannan"
  }, {
    "id": "66",
    "pid": "5",
    "name": "嘉峪关",
    "ad_name": "嘉峪关市",
    "letter": "jiayuguan"
  }, {
    "id": "67",
    "pid": "5",
    "name": "金昌",
    "ad_name": "金昌市",
    "letter": "jinchang"
  }, {
    "id": "68",
    "pid": "5",
    "name": "酒泉",
    "ad_name": "酒泉市",
    "letter": "jiuquan"
  }, {
    "id": "69",
    "pid": "5",
    "name": "临夏",
    "ad_name": "临夏回族自治州",
    "letter": "linxia"
  }, {
    "id": "70",
    "pid": "5",
    "name": "陇南",
    "ad_name": "陇南市",
    "letter": "longnan"
  }, {
    "id": "71",
    "pid": "5",
    "name": "平凉",
    "ad_name": "平凉市",
    "letter": "pingliang"
  }, {
    "id": "72",
    "pid": "5",
    "name": "庆阳",
    "ad_name": "庆阳市",
    "letter": "qingyang"
  }, {
    "id": "73",
    "pid": "5",
    "name": "天水",
    "ad_name": "天水市",
    "letter": "tianshui"
  }, {
    "id": "74",
    "pid": "5",
    "name": "武威",
    "ad_name": "武威市",
    "letter": "wuwei"
  }, {
    "id": "75",
    "pid": "5",
    "name": "张掖",
    "ad_name": "张掖市",
    "letter": "zhangye"
  }]
}, {
  "id": "6",
  "pid": "1",
  "name": "广东",
  "ad_name": "广东省",
  "letter": "guangdong",
  "has_children": 1,
  "children": [{
    "id": "6",
    "pid": "1",
    "name": "广东",
    "ad_name": "广东省",
    "letter": "guangdong"
  }, {
    "id": "76",
    "pid": "6",
    "name": "广州",
    "ad_name": "广州市",
    "letter": "guangzhou"
  }, {
    "id": "77",
    "pid": "6",
    "name": "深圳",
    "ad_name": "深圳市",
    "letter": "shenzhen"
  }, {
    "id": "78",
    "pid": "6",
    "name": "潮州",
    "ad_name": "潮州市",
    "letter": "chaozhou"
  }, {
    "id": "79",
    "pid": "6",
    "name": "东莞",
    "ad_name": "东莞市",
    "letter": "dongguan"
  }, {
    "id": "80",
    "pid": "6",
    "name": "佛山",
    "ad_name": "佛山市",
    "letter": "foshan"
  }, {
    "id": "81",
    "pid": "6",
    "name": "河源",
    "ad_name": "河源市",
    "letter": "heyuan"
  }, {
    "id": "82",
    "pid": "6",
    "name": "惠州",
    "ad_name": "惠州市",
    "letter": "huizhou"
  }, {
    "id": "83",
    "pid": "6",
    "name": "江门",
    "ad_name": "江门市",
    "letter": "jiangmen"
  }, {
    "id": "84",
    "pid": "6",
    "name": "揭阳",
    "ad_name": "揭阳市",
    "letter": "jieyang"
  }, {
    "id": "85",
    "pid": "6",
    "name": "茂名",
    "ad_name": "茂名市",
    "letter": "maoming"
  }, {
    "id": "86",
    "pid": "6",
    "name": "梅州",
    "ad_name": "梅州市",
    "letter": "meizhou"
  }, {
    "id": "87",
    "pid": "6",
    "name": "清远",
    "ad_name": "清远市",
    "letter": "qingyuan"
  }, {
    "id": "88",
    "pid": "6",
    "name": "汕头",
    "ad_name": "汕头市",
    "letter": "shantou"
  }, {
    "id": "89",
    "pid": "6",
    "name": "汕尾",
    "ad_name": "汕尾市",
    "letter": "shanwei"
  }, {
    "id": "90",
    "pid": "6",
    "name": "韶关",
    "ad_name": "韶关市",
    "letter": "shaoguan"
  }, {
    "id": "91",
    "pid": "6",
    "name": "阳江",
    "ad_name": "阳江市",
    "letter": "yangjiang"
  }, {
    "id": "92",
    "pid": "6",
    "name": "云浮",
    "ad_name": "云浮市",
    "letter": "yunfu"
  }, {
    "id": "93",
    "pid": "6",
    "name": "湛江",
    "ad_name": "湛江市",
    "letter": "zhanjiang"
  }, {
    "id": "94",
    "pid": "6",
    "name": "肇庆",
    "ad_name": "肇庆市",
    "letter": "zhaoqing"
  }, {
    "id": "95",
    "pid": "6",
    "name": "中山",
    "ad_name": "中山市",
    "letter": "zhongshan"
  }, {
    "id": "96",
    "pid": "6",
    "name": "珠海",
    "ad_name": "珠海市",
    "letter": "zhuhai"
  }]
}, {
  "id": "7",
  "pid": "1",
  "name": "广西",
  "ad_name": "广西壮族自治区",
  "letter": "guangxi",
  "has_children": 1,
  "children": [{
    "id": "7",
    "pid": "1",
    "name": "广西",
    "ad_name": "广西壮族自治区",
    "letter": "guangxi"
  }, {
    "id": "97",
    "pid": "7",
    "name": "南宁",
    "ad_name": "南宁市",
    "letter": "nanning"
  }, {
    "id": "98",
    "pid": "7",
    "name": "桂林",
    "ad_name": "桂林市",
    "letter": "guilin"
  }, {
    "id": "99",
    "pid": "7",
    "name": "百色",
    "ad_name": "百色市",
    "letter": "baise"
  }, {
    "id": "100",
    "pid": "7",
    "name": "北海",
    "ad_name": "北海市",
    "letter": "beihai"
  }, {
    "id": "101",
    "pid": "7",
    "name": "崇左",
    "ad_name": "崇左市",
    "letter": "chongzuo"
  }, {
    "id": "102",
    "pid": "7",
    "name": "防城港",
    "ad_name": "防城港市",
    "letter": "fangchenggang"
  }, {
    "id": "103",
    "pid": "7",
    "name": "贵港",
    "ad_name": "贵港市",
    "letter": "guigang"
  }, {
    "id": "104",
    "pid": "7",
    "name": "河池",
    "ad_name": "河池市",
    "letter": "hechi"
  }, {
    "id": "105",
    "pid": "7",
    "name": "贺州",
    "ad_name": "贺州市",
    "letter": "hezhou"
  }, {
    "id": "106",
    "pid": "7",
    "name": "来宾",
    "ad_name": "来宾市",
    "letter": "laibin"
  }, {
    "id": "107",
    "pid": "7",
    "name": "柳州",
    "ad_name": "柳州市",
    "letter": "liuzhou"
  }, {
    "id": "108",
    "pid": "7",
    "name": "钦州",
    "ad_name": "钦州市",
    "letter": "qinzhou"
  }, {
    "id": "109",
    "pid": "7",
    "name": "梧州",
    "ad_name": "梧州市",
    "letter": "wuzhou"
  }, {
    "id": "110",
    "pid": "7",
    "name": "玉林",
    "ad_name": "玉林市",
    "letter": "yulin"
  }]
}, {
  "id": "8",
  "pid": "1",
  "name": "贵州",
  "ad_name": "贵州省",
  "letter": "guizhou",
  "has_children": 1,
  "children": [{
    "id": "8",
    "pid": "1",
    "name": "贵州",
    "ad_name": "贵州省",
    "letter": "guizhou"
  }, {
    "id": "111",
    "pid": "8",
    "name": "贵阳",
    "ad_name": "贵阳市",
    "letter": "guiyang"
  }, {
    "id": "112",
    "pid": "8",
    "name": "安顺",
    "ad_name": "安顺市",
    "letter": "anshun"
  }, {
    "id": "113",
    "pid": "8",
    "name": "毕节",
    "ad_name": "毕节市",
    "letter": "bijie"
  }, {
    "id": "114",
    "pid": "8",
    "name": "六盘水",
    "ad_name": "六盘水市",
    "letter": "liupanshui"
  }, {
    "id": "115",
    "pid": "8",
    "name": "黔东南",
    "ad_name": "黔东南苗族侗族自治州",
    "letter": "qiandongnan"
  }, {
    "id": "116",
    "pid": "8",
    "name": "黔南",
    "ad_name": "黔南布依族苗族自治州",
    "letter": "qiannan"
  }, {
    "id": "117",
    "pid": "8",
    "name": "黔西南",
    "ad_name": "黔西南布依族苗族自治州",
    "letter": "qianxinan"
  }, {
    "id": "118",
    "pid": "8",
    "name": "铜仁",
    "ad_name": "铜仁市",
    "letter": "tongren"
  }, {
    "id": "119",
    "pid": "8",
    "name": "遵义",
    "ad_name": "遵义市",
    "letter": "zunyi"
  }]
}, {
  "id": "9",
  "pid": "1",
  "name": "海南",
  "ad_name": "海南省",
  "letter": "hainan",
  "has_children": 1,
  "children": [{
    "id": "9",
    "pid": "1",
    "name": "海南",
    "ad_name": "海南省",
    "letter": "hainan"
  }, {
    "id": "120",
    "pid": "9",
    "name": "海口",
    "ad_name": "海口市",
    "letter": "haikou"
  }, {
    "id": "121",
    "pid": "9",
    "name": "三亚",
    "ad_name": "三亚市",
    "letter": "sanya"
  }, {
    "id": "122",
    "pid": "9",
    "name": "白沙",
    "ad_name": "白沙黎族自治县",
    "letter": "baisha"
  }, {
    "id": "123",
    "pid": "9",
    "name": "保亭",
    "ad_name": "保亭黎族苗族自治县",
    "letter": "baoting"
  }, {
    "id": "124",
    "pid": "9",
    "name": "昌江",
    "ad_name": "昌江",
    "letter": "changjiang"
  }, {
    "id": "125",
    "pid": "9",
    "name": "澄迈县",
    "ad_name": "澄迈县",
    "letter": "chengmai"
  }, {
    "id": "126",
    "pid": "9",
    "name": "定安县",
    "ad_name": "定安县",
    "letter": "dingan"
  }, {
    "id": "127",
    "pid": "9",
    "name": "东方",
    "ad_name": "东方市",
    "letter": "dongfang"
  }, {
    "id": "128",
    "pid": "9",
    "name": "乐东",
    "ad_name": "乐东黎族自治县",
    "letter": "ledong"
  }, {
    "id": "129",
    "pid": "9",
    "name": "临高县",
    "ad_name": "临高县",
    "letter": "lingao"
  }, {
    "id": "130",
    "pid": "9",
    "name": "陵水",
    "ad_name": "陵水黎族自治县",
    "letter": "lingshui"
  }, {
    "id": "131",
    "pid": "9",
    "name": "琼海",
    "ad_name": "琼海市",
    "letter": "qionghai"
  }, {
    "id": "132",
    "pid": "9",
    "name": "琼中",
    "ad_name": "琼中黎族苗族自治县",
    "letter": "qiongzhong"
  }, {
    "id": "133",
    "pid": "9",
    "name": "屯昌县",
    "ad_name": "屯昌县",
    "letter": "tunchang"
  }, {
    "id": "134",
    "pid": "9",
    "name": "万宁",
    "ad_name": "万宁市",
    "letter": "wanning"
  }, {
    "id": "135",
    "pid": "9",
    "name": "文昌",
    "ad_name": "文昌市",
    "letter": "wenchang"
  }, {
    "id": "136",
    "pid": "9",
    "name": "五指山",
    "ad_name": "五指山市",
    "letter": "wuzhishan"
  }, {
    "id": "137",
    "pid": "9",
    "name": "儋州",
    "ad_name": "儋州市",
    "letter": "danzhou"
  }]
}, {
  "id": "10",
  "pid": "1",
  "name": "河北",
  "ad_name": "河北省",
  "letter": "hebei",
  "has_children": 1,
  "children": [{
    "id": "10",
    "pid": "1",
    "name": "河北",
    "ad_name": "河北省",
    "letter": "hebei"
  }, {
    "id": "138",
    "pid": "10",
    "name": "石家庄",
    "ad_name": "石家庄市",
    "letter": "shijiazhuang"
  }, {
    "id": "139",
    "pid": "10",
    "name": "保定",
    "ad_name": "保定市",
    "letter": "baoding"
  }, {
    "id": "140",
    "pid": "10",
    "name": "沧州",
    "ad_name": "沧州市",
    "letter": "cangzhou"
  }, {
    "id": "141",
    "pid": "10",
    "name": "承德",
    "ad_name": "承德市",
    "letter": "chengde"
  }, {
    "id": "142",
    "pid": "10",
    "name": "邯郸",
    "ad_name": "邯郸市",
    "letter": "handan"
  }, {
    "id": "143",
    "pid": "10",
    "name": "衡水",
    "ad_name": "衡水市",
    "letter": "hengshui"
  }, {
    "id": "144",
    "pid": "10",
    "name": "廊坊",
    "ad_name": "廊坊市",
    "letter": "langfang"
  }, {
    "id": "145",
    "pid": "10",
    "name": "秦皇岛",
    "ad_name": "秦皇岛市",
    "letter": "qinhuangdao"
  }, {
    "id": "146",
    "pid": "10",
    "name": "唐山",
    "ad_name": "唐山市",
    "letter": "tangshan"
  }, {
    "id": "147",
    "pid": "10",
    "name": "邢台",
    "ad_name": "邢台市",
    "letter": "xingtai"
  }, {
    "id": "148",
    "pid": "10",
    "name": "张家口",
    "ad_name": "张家口市",
    "letter": "zhangjiakou"
  }]
}, {
  "id": "11",
  "pid": "1",
  "name": "河南",
  "ad_name": "河南省",
  "letter": "henan",
  "has_children": 1,
  "children": [{
    "id": "11",
    "pid": "1",
    "name": "河南",
    "ad_name": "河南省",
    "letter": "henan"
  }, {
    "id": "149",
    "pid": "11",
    "name": "郑州",
    "ad_name": "郑州市",
    "letter": "zhengzhou"
  }, {
    "id": "150",
    "pid": "11",
    "name": "洛阳",
    "ad_name": "洛阳市",
    "letter": "luoyang"
  }, {
    "id": "151",
    "pid": "11",
    "name": "开封",
    "ad_name": "开封市",
    "letter": "kaifeng"
  }, {
    "id": "152",
    "pid": "11",
    "name": "安阳",
    "ad_name": "安阳市",
    "letter": "anyang"
  }, {
    "id": "153",
    "pid": "11",
    "name": "鹤壁",
    "ad_name": "鹤壁市",
    "letter": "hebi"
  }, {
    "id": "154",
    "pid": "11",
    "name": "济源",
    "ad_name": "济源市",
    "letter": "jiyuan"
  }, {
    "id": "155",
    "pid": "11",
    "name": "焦作",
    "ad_name": "焦作市",
    "letter": "jiaozuo"
  }, {
    "id": "156",
    "pid": "11",
    "name": "南阳",
    "ad_name": "南阳市",
    "letter": "nanyang"
  }, {
    "id": "157",
    "pid": "11",
    "name": "平顶山",
    "ad_name": "平顶山市",
    "letter": "pingdingshan"
  }, {
    "id": "158",
    "pid": "11",
    "name": "三门峡",
    "ad_name": "三门峡市",
    "letter": "sanmenxia"
  }, {
    "id": "159",
    "pid": "11",
    "name": "商丘",
    "ad_name": "商丘市",
    "letter": "shangqiu"
  }, {
    "id": "160",
    "pid": "11",
    "name": "新乡",
    "ad_name": "新乡市",
    "letter": "xinxiang"
  }, {
    "id": "161",
    "pid": "11",
    "name": "信阳",
    "ad_name": "信阳市",
    "letter": "xinyang"
  }, {
    "id": "162",
    "pid": "11",
    "name": "许昌",
    "ad_name": "许昌市",
    "letter": "xuchang"
  }, {
    "id": "163",
    "pid": "11",
    "name": "周口",
    "ad_name": "周口市",
    "letter": "zhoukou"
  }, {
    "id": "164",
    "pid": "11",
    "name": "驻马店",
    "ad_name": "驻马店市",
    "letter": "zhumadian"
  }, {
    "id": "165",
    "pid": "11",
    "name": "漯河",
    "ad_name": "漯河市",
    "letter": "luohe"
  }, {
    "id": "166",
    "pid": "11",
    "name": "濮阳",
    "ad_name": "濮阳市",
    "letter": "puyang"
  }]
}, {
  "id": "12",
  "pid": "1",
  "name": "黑龙江",
  "ad_name": "黑龙江省",
  "letter": "heilongjiang",
  "has_children": 1,
  "children": [{
    "id": "12",
    "pid": "1",
    "name": "黑龙江",
    "ad_name": "黑龙江省",
    "letter": "heilongjiang"
  }, {
    "id": "167",
    "pid": "12",
    "name": "哈尔滨",
    "ad_name": "哈尔滨市",
    "letter": "haerbin"
  }, {
    "id": "168",
    "pid": "12",
    "name": "大庆",
    "ad_name": "大庆市",
    "letter": "daqing"
  }, {
    "id": "169",
    "pid": "12",
    "name": "大兴安岭",
    "ad_name": "大兴安岭地区",
    "letter": "daxinganling"
  }, {
    "id": "170",
    "pid": "12",
    "name": "鹤岗",
    "ad_name": "鹤岗市",
    "letter": "hegang"
  }, {
    "id": "171",
    "pid": "12",
    "name": "黑河",
    "ad_name": "黑河市",
    "letter": "heihe"
  }, {
    "id": "172",
    "pid": "12",
    "name": "鸡西",
    "ad_name": "鸡西市",
    "letter": "jixi"
  }, {
    "id": "173",
    "pid": "12",
    "name": "佳木斯",
    "ad_name": "佳木斯市",
    "letter": "jiamusi"
  }, {
    "id": "174",
    "pid": "12",
    "name": "牡丹江",
    "ad_name": "牡丹江市",
    "letter": "mudanjiang"
  }, {
    "id": "175",
    "pid": "12",
    "name": "七台河",
    "ad_name": "七台河市",
    "letter": "qitaihe"
  }, {
    "id": "176",
    "pid": "12",
    "name": "齐齐哈尔",
    "ad_name": "齐齐哈尔市",
    "letter": "jijihaer"
  }, {
    "id": "177",
    "pid": "12",
    "name": "双鸭山",
    "ad_name": "双鸭山市",
    "letter": "shuangyashan"
  }, {
    "id": "178",
    "pid": "12",
    "name": "绥化",
    "ad_name": "绥化市",
    "letter": "suihua"
  }, {
    "id": "179",
    "pid": "12",
    "name": "伊春",
    "ad_name": "伊春市",
    "letter": "yichun"
  }]
}, {
  "id": "13",
  "pid": "1",
  "name": "湖北",
  "ad_name": "湖北省",
  "letter": "hubei",
  "has_children": 1,
  "children": [{
    "id": "13",
    "pid": "1",
    "name": "湖北",
    "ad_name": "湖北省",
    "letter": "hubei"
  }, {
    "id": "180",
    "pid": "13",
    "name": "武汉",
    "ad_name": "武汉市",
    "letter": "wuhan"
  }, {
    "id": "181",
    "pid": "13",
    "name": "仙桃",
    "ad_name": "仙桃市",
    "letter": "xiantao"
  }, {
    "id": "182",
    "pid": "13",
    "name": "鄂州",
    "ad_name": "鄂州市",
    "letter": "ezhou"
  }, {
    "id": "183",
    "pid": "13",
    "name": "黄冈",
    "ad_name": "黄冈市",
    "letter": "huanggang"
  }, {
    "id": "184",
    "pid": "13",
    "name": "黄石",
    "ad_name": "黄石市",
    "letter": "huangshi"
  }, {
    "id": "185",
    "pid": "13",
    "name": "荆门",
    "ad_name": "荆门市",
    "letter": "jingmen"
  }, {
    "id": "186",
    "pid": "13",
    "name": "荆州",
    "ad_name": "荆州市",
    "letter": "jingzhou"
  }, {
    "id": "187",
    "pid": "13",
    "name": "潜江",
    "ad_name": "潜江市",
    "letter": "qianjiang"
  }, {
    "id": "188",
    "pid": "13",
    "name": "神农架林区",
    "ad_name": "神农架林区",
    "letter": "shennongjia"
  }, {
    "id": "189",
    "pid": "13",
    "name": "十堰",
    "ad_name": "十堰市",
    "letter": "shiyan"
  }, {
    "id": "190",
    "pid": "13",
    "name": "随州",
    "ad_name": "随州市",
    "letter": "suizhou"
  }, {
    "id": "191",
    "pid": "13",
    "name": "天门",
    "ad_name": "天门市",
    "letter": "tianmen"
  }, {
    "id": "192",
    "pid": "13",
    "name": "咸宁",
    "ad_name": "咸宁市",
    "letter": "xianning"
  }, {
    "id": "193",
    "pid": "13",
    "name": "襄阳",
    "ad_name": "襄阳市",
    "letter": "xiangfan"
  }, {
    "id": "194",
    "pid": "13",
    "name": "孝感",
    "ad_name": "孝感市",
    "letter": "xiaogan"
  }, {
    "id": "195",
    "pid": "13",
    "name": "宜昌",
    "ad_name": "宜昌市",
    "letter": "yichang"
  }, {
    "id": "196",
    "pid": "13",
    "name": "恩施",
    "ad_name": "恩施",
    "letter": "enshi"
  }]
}, {
  "id": "14",
  "pid": "1",
  "name": "湖南",
  "ad_name": "湖南省",
  "letter": "hunan",
  "has_children": 1,
  "children": [{
    "id": "14",
    "pid": "1",
    "name": "湖南",
    "ad_name": "湖南省",
    "letter": "hunan"
  }, {
    "id": "197",
    "pid": "14",
    "name": "长沙",
    "ad_name": "长沙市",
    "letter": "changsha"
  }, {
    "id": "198",
    "pid": "14",
    "name": "张家界",
    "ad_name": "张家界市",
    "letter": "zhangjiajie"
  }, {
    "id": "199",
    "pid": "14",
    "name": "常德",
    "ad_name": "常德市",
    "letter": "changde"
  }, {
    "id": "200",
    "pid": "14",
    "name": "郴州",
    "ad_name": "郴州市",
    "letter": "chenzhou"
  }, {
    "id": "201",
    "pid": "14",
    "name": "衡阳",
    "ad_name": "衡阳市",
    "letter": "hengyang"
  }, {
    "id": "202",
    "pid": "14",
    "name": "怀化",
    "ad_name": "怀化市",
    "letter": "huaihua"
  }, {
    "id": "203",
    "pid": "14",
    "name": "娄底",
    "ad_name": "娄底市",
    "letter": "loudi"
  }, {
    "id": "204",
    "pid": "14",
    "name": "邵阳",
    "ad_name": "邵阳市",
    "letter": "shaoyang"
  }, {
    "id": "205",
    "pid": "14",
    "name": "湘潭",
    "ad_name": "湘潭市",
    "letter": "xiangtan"
  }, {
    "id": "206",
    "pid": "14",
    "name": "湘西",
    "ad_name": "湘西土家族苗族自治州",
    "letter": "xiangxi"
  }, {
    "id": "207",
    "pid": "14",
    "name": "益阳",
    "ad_name": "益阳市",
    "letter": "yiyang"
  }, {
    "id": "208",
    "pid": "14",
    "name": "永州",
    "ad_name": "永州市",
    "letter": "yongzhou"
  }, {
    "id": "209",
    "pid": "14",
    "name": "岳阳",
    "ad_name": "岳阳市",
    "letter": "yueyang"
  }, {
    "id": "210",
    "pid": "14",
    "name": "株洲",
    "ad_name": "株洲市",
    "letter": "zhuzhou"
  }]
}, {
  "id": "15",
  "pid": "1",
  "name": "吉林",
  "ad_name": "吉林省",
  "letter": "jilin",
  "has_children": 1,
  "children": [{
    "id": "15",
    "pid": "1",
    "name": "吉林",
    "ad_name": "吉林省",
    "letter": "jilin"
  }, {
    "id": "211",
    "pid": "15",
    "name": "长春",
    "ad_name": "长春市",
    "letter": "changchun"
  }, {
    "id": "212",
    "pid": "15",
    "name": "吉林",
    "ad_name": "吉林市",
    "letter": "jilinshi"
  }, {
    "id": "213",
    "pid": "15",
    "name": "白城",
    "ad_name": "白城市",
    "letter": "baicheng"
  }, {
    "id": "214",
    "pid": "15",
    "name": "白山",
    "ad_name": "白山市",
    "letter": "baishan"
  }, {
    "id": "215",
    "pid": "15",
    "name": "辽源",
    "ad_name": "辽源市",
    "letter": "liaoyuan"
  }, {
    "id": "216",
    "pid": "15",
    "name": "四平",
    "ad_name": "四平市",
    "letter": "siping"
  }, {
    "id": "217",
    "pid": "15",
    "name": "松原",
    "ad_name": "松原市",
    "letter": "songyuan"
  }, {
    "id": "218",
    "pid": "15",
    "name": "通化",
    "ad_name": "通化市",
    "letter": "tonghua"
  }, {
    "id": "219",
    "pid": "15",
    "name": "延边",
    "ad_name": "延边朝鲜族自治州",
    "letter": "yanbian"
  }]
}, {
  "id": "16",
  "pid": "1",
  "name": "江苏",
  "ad_name": "江苏省",
  "letter": "jiangsu",
  "has_children": 1,
  "children": [{
    "id": "16",
    "pid": "1",
    "name": "江苏",
    "ad_name": "江苏省",
    "letter": "jiangsu"
  }, {
    "id": "220",
    "pid": "16",
    "name": "南京",
    "ad_name": "南京市",
    "letter": "nanjing"
  }, {
    "id": "221",
    "pid": "16",
    "name": "苏州",
    "ad_name": "苏州市",
    "letter": "suzhou"
  }, {
    "id": "222",
    "pid": "16",
    "name": "无锡",
    "ad_name": "无锡市",
    "letter": "wuxi"
  }, {
    "id": "223",
    "pid": "16",
    "name": "常州",
    "ad_name": "常州市",
    "letter": "changzhou"
  }, {
    "id": "224",
    "pid": "16",
    "name": "淮安",
    "ad_name": "淮安市",
    "letter": "huaian"
  }, {
    "id": "225",
    "pid": "16",
    "name": "连云港",
    "ad_name": "连云港市",
    "letter": "lianyungang"
  }, {
    "id": "226",
    "pid": "16",
    "name": "南通",
    "ad_name": "南通市",
    "letter": "nantong"
  }, {
    "id": "227",
    "pid": "16",
    "name": "宿迁",
    "ad_name": "宿迁市",
    "letter": "suqian"
  }, {
    "id": "228",
    "pid": "16",
    "name": "泰州",
    "ad_name": "泰州市",
    "letter": "taizhou"
  }, {
    "id": "229",
    "pid": "16",
    "name": "徐州",
    "ad_name": "徐州市",
    "letter": "xuzhou"
  }, {
    "id": "230",
    "pid": "16",
    "name": "盐城",
    "ad_name": "盐城市",
    "letter": "yancheng"
  }, {
    "id": "231",
    "pid": "16",
    "name": "扬州",
    "ad_name": "扬州市",
    "letter": "yangzhou"
  }, {
    "id": "232",
    "pid": "16",
    "name": "镇江",
    "ad_name": "镇江市",
    "letter": "zhenjiang"
  }]
}, {
  "id": "17",
  "pid": "1",
  "name": "江西",
  "ad_name": "江西省",
  "letter": "jiangxi",
  "has_children": 1,
  "children": [{
    "id": "17",
    "pid": "1",
    "name": "江西",
    "ad_name": "江西省",
    "letter": "jiangxi"
  }, {
    "id": "233",
    "pid": "17",
    "name": "南昌",
    "ad_name": "南昌市",
    "letter": "nanchang"
  }, {
    "id": "234",
    "pid": "17",
    "name": "抚州",
    "ad_name": "抚州市",
    "letter": "jiangxifuzhou"
  }, {
    "id": "235",
    "pid": "17",
    "name": "赣州",
    "ad_name": "赣州市",
    "letter": "ganzhou"
  }, {
    "id": "236",
    "pid": "17",
    "name": "吉安",
    "ad_name": "吉安市",
    "letter": "jian"
  }, {
    "id": "237",
    "pid": "17",
    "name": "景德镇",
    "ad_name": "景德镇市",
    "letter": "jingdezhen"
  }, {
    "id": "238",
    "pid": "17",
    "name": "九江",
    "ad_name": "九江市",
    "letter": "jiujiang"
  }, {
    "id": "239",
    "pid": "17",
    "name": "萍乡",
    "ad_name": "萍乡市",
    "letter": "pingxiang"
  }, {
    "id": "240",
    "pid": "17",
    "name": "上饶",
    "ad_name": "上饶市",
    "letter": "shangrao"
  }, {
    "id": "241",
    "pid": "17",
    "name": "新余",
    "ad_name": "新余市",
    "letter": "xinyu"
  }, {
    "id": "242",
    "pid": "17",
    "name": "宜春",
    "ad_name": "宜春市",
    "letter": "jxyichun"
  }, {
    "id": "243",
    "pid": "17",
    "name": "鹰潭",
    "ad_name": "鹰潭市",
    "letter": "yingtan"
  }]
}, {
  "id": "18",
  "pid": "1",
  "name": "辽宁",
  "ad_name": "辽宁省",
  "letter": "liaoning",
  "has_children": 1,
  "children": [{
    "id": "18",
    "pid": "1",
    "name": "辽宁",
    "ad_name": "辽宁省",
    "letter": "liaoning"
  }, {
    "id": "244",
    "pid": "18",
    "name": "沈阳",
    "ad_name": "沈阳市",
    "letter": "shenyang"
  }, {
    "id": "245",
    "pid": "18",
    "name": "大连",
    "ad_name": "大连市",
    "letter": "dalian"
  }, {
    "id": "246",
    "pid": "18",
    "name": "鞍山",
    "ad_name": "鞍山市",
    "letter": "anshan"
  }, {
    "id": "247",
    "pid": "18",
    "name": "本溪",
    "ad_name": "本溪市",
    "letter": "benxi"
  }, {
    "id": "248",
    "pid": "18",
    "name": "朝阳",
    "ad_name": "朝阳市",
    "letter": "chaoyang"
  }, {
    "id": "249",
    "pid": "18",
    "name": "丹东",
    "ad_name": "丹东市",
    "letter": "dandong"
  }, {
    "id": "250",
    "pid": "18",
    "name": "抚顺",
    "ad_name": "抚顺市",
    "letter": "fushun"
  }, {
    "id": "251",
    "pid": "18",
    "name": "阜新",
    "ad_name": "阜新市",
    "letter": "fuxin"
  }, {
    "id": "252",
    "pid": "18",
    "name": "葫芦岛",
    "ad_name": "葫芦岛市",
    "letter": "huludao"
  }, {
    "id": "253",
    "pid": "18",
    "name": "锦州",
    "ad_name": "锦州市",
    "letter": "jinzhou"
  }, {
    "id": "254",
    "pid": "18",
    "name": "辽阳",
    "ad_name": "辽阳市",
    "letter": "liaoyang"
  }, {
    "id": "255",
    "pid": "18",
    "name": "盘锦",
    "ad_name": "盘锦市",
    "letter": "panjin"
  }, {
    "id": "256",
    "pid": "18",
    "name": "铁岭",
    "ad_name": "铁岭市",
    "letter": "tieling"
  }, {
    "id": "257",
    "pid": "18",
    "name": "营口",
    "ad_name": "营口市",
    "letter": "yingkou"
  }]
}, {
  "id": "19",
  "pid": "1",
  "name": "内蒙古",
  "ad_name": "内蒙古自治区",
  "letter": "neimenggu",
  "has_children": 1,
  "children": [{
    "id": "19",
    "pid": "1",
    "name": "内蒙古",
    "ad_name": "内蒙古自治区",
    "letter": "neimenggu"
  }, {
    "id": "258",
    "pid": "19",
    "name": "呼和浩特",
    "ad_name": "呼和浩特市",
    "letter": "huhehaote"
  }, {
    "id": "259",
    "pid": "19",
    "name": "阿拉善盟",
    "ad_name": "阿拉善盟",
    "letter": "alashan"
  }, {
    "id": "260",
    "pid": "19",
    "name": "巴彦淖尔盟",
    "ad_name": "巴彦淖尔市",
    "letter": "bayannaoer"
  }, {
    "id": "261",
    "pid": "19",
    "name": "包头",
    "ad_name": "包头市",
    "letter": "baotou"
  }, {
    "id": "262",
    "pid": "19",
    "name": "赤峰",
    "ad_name": "赤峰市",
    "letter": "chifeng"
  }, {
    "id": "263",
    "pid": "19",
    "name": "鄂尔多斯",
    "ad_name": "鄂尔多斯市",
    "letter": "eerduosi"
  }, {
    "id": "264",
    "pid": "19",
    "name": "呼伦贝尔",
    "ad_name": "呼伦贝尔市",
    "letter": "hulunbeier"
  }, {
    "id": "265",
    "pid": "19",
    "name": "通辽",
    "ad_name": "通辽市",
    "letter": "tongliao"
  }, {
    "id": "266",
    "pid": "19",
    "name": "乌海",
    "ad_name": "乌海市",
    "letter": "wuhai"
  }, {
    "id": "267",
    "pid": "19",
    "name": "乌兰察布市",
    "ad_name": "乌兰察布市",
    "letter": "wulanchabu"
  }, {
    "id": "268",
    "pid": "19",
    "name": "锡林郭勒盟",
    "ad_name": "锡林郭勒盟",
    "letter": "xilingele"
  }, {
    "id": "269",
    "pid": "19",
    "name": "兴安盟",
    "ad_name": "兴安盟",
    "letter": "xingan"
  }]
}, {
  "id": "20",
  "pid": "1",
  "name": "宁夏",
  "ad_name": "宁夏回族自治区",
  "letter": "ningxia",
  "has_children": 1,
  "children": [{
    "id": "20",
    "pid": "1",
    "name": "宁夏",
    "ad_name": "宁夏回族自治区",
    "letter": "ningxia"
  }, {
    "id": "270",
    "pid": "20",
    "name": "银川",
    "ad_name": "银川市",
    "letter": "yinchuan"
  }, {
    "id": "271",
    "pid": "20",
    "name": "固原",
    "ad_name": "固原市",
    "letter": "guyuan"
  }, {
    "id": "272",
    "pid": "20",
    "name": "石嘴山",
    "ad_name": "石嘴山市",
    "letter": "shizuishan"
  }, {
    "id": "273",
    "pid": "20",
    "name": "吴忠",
    "ad_name": "吴忠市",
    "letter": "wuzhong"
  }, {
    "id": "274",
    "pid": "20",
    "name": "中卫",
    "ad_name": "中卫市",
    "letter": "zhongwei"
  }]
}, {
  "id": "21",
  "pid": "1",
  "name": "青海",
  "ad_name": "青海省",
  "letter": "qinghai",
  "has_children": 1,
  "children": [{
    "id": "21",
    "pid": "1",
    "name": "青海",
    "ad_name": "青海省",
    "letter": "qinghai"
  }, {
    "id": "275",
    "pid": "21",
    "name": "西宁",
    "ad_name": "西宁市",
    "letter": "xining"
  }, {
    "id": "276",
    "pid": "21",
    "name": "果洛",
    "ad_name": "果洛藏族自治州",
    "letter": "guoluo"
  }, {
    "id": "277",
    "pid": "21",
    "name": "海北",
    "ad_name": "海北藏族自治州",
    "letter": "haibei"
  }, {
    "id": "278",
    "pid": "21",
    "name": "海东",
    "ad_name": "海东市",
    "letter": "haidong"
  }, {
    "id": "279",
    "pid": "21",
    "name": "海南州",
    "ad_name": "海南藏族自治州",
    "letter": "hainanzhou"
  }, {
    "id": "280",
    "pid": "21",
    "name": "海西",
    "ad_name": "海西蒙古族藏族自治州",
    "letter": "haixi"
  }, {
    "id": "281",
    "pid": "21",
    "name": "黄南",
    "ad_name": "黄南藏族自治州",
    "letter": "huangnan"
  }, {
    "id": "282",
    "pid": "21",
    "name": "玉树",
    "ad_name": "玉树",
    "letter": "yushu"
  }]
}, {
  "id": "22",
  "pid": "1",
  "name": "山东",
  "ad_name": "山东省",
  "letter": "shandong",
  "has_children": 1,
  "children": [{
    "id": "22",
    "pid": "1",
    "name": "山东",
    "ad_name": "山东省",
    "letter": "shandong"
  }, {
    "id": "283",
    "pid": "22",
    "name": "济南",
    "ad_name": "济南市",
    "letter": "jinan"
  }, {
    "id": "284",
    "pid": "22",
    "name": "青岛",
    "ad_name": "青岛市",
    "letter": "qingdao"
  }, {
    "id": "285",
    "pid": "22",
    "name": "滨州",
    "ad_name": "滨州市",
    "letter": "binzhou"
  }, {
    "id": "286",
    "pid": "22",
    "name": "德州",
    "ad_name": "德州市",
    "letter": "dezhou"
  }, {
    "id": "287",
    "pid": "22",
    "name": "东营",
    "ad_name": "东营市",
    "letter": "dongying"
  }, {
    "id": "288",
    "pid": "22",
    "name": "菏泽",
    "ad_name": "菏泽市",
    "letter": "heze"
  }, {
    "id": "289",
    "pid": "22",
    "name": "济宁",
    "ad_name": "济宁市",
    "letter": "jining"
  }, {
    "id": "291",
    "pid": "22",
    "name": "聊城",
    "ad_name": "聊城市",
    "letter": "liaocheng"
  }, {
    "id": "292",
    "pid": "22",
    "name": "临沂",
    "ad_name": "临沂市",
    "letter": "linyi"
  }, {
    "id": "293",
    "pid": "22",
    "name": "日照",
    "ad_name": "日照市",
    "letter": "rizhao"
  }, {
    "id": "294",
    "pid": "22",
    "name": "泰安",
    "ad_name": "泰安市",
    "letter": "taian"
  }, {
    "id": "295",
    "pid": "22",
    "name": "威海",
    "ad_name": "威海市",
    "letter": "weihai"
  }, {
    "id": "296",
    "pid": "22",
    "name": "潍坊",
    "ad_name": "潍坊市",
    "letter": "weifang"
  }, {
    "id": "297",
    "pid": "22",
    "name": "烟台",
    "ad_name": "烟台市",
    "letter": "yantai"
  }, {
    "id": "298",
    "pid": "22",
    "name": "枣庄",
    "ad_name": "枣庄市",
    "letter": "zaozhuang"
  }, {
    "id": "299",
    "pid": "22",
    "name": "淄博",
    "ad_name": "淄博市",
    "letter": "zibo"
  }]
}, {
  "id": "23",
  "pid": "1",
  "name": "山西",
  "ad_name": "山西省",
  "letter": "shanxi",
  "has_children": 1,
  "children": [{
    "id": "23",
    "pid": "1",
    "name": "山西",
    "ad_name": "山西省",
    "letter": "shanxi"
  }, {
    "id": "300",
    "pid": "23",
    "name": "太原",
    "ad_name": "太原市",
    "letter": "taiyuan"
  }, {
    "id": "301",
    "pid": "23",
    "name": "长治",
    "ad_name": "长治市",
    "letter": "changzhi"
  }, {
    "id": "302",
    "pid": "23",
    "name": "大同",
    "ad_name": "大同市",
    "letter": "datong"
  }, {
    "id": "303",
    "pid": "23",
    "name": "晋城",
    "ad_name": "晋城市",
    "letter": "jincheng"
  }, {
    "id": "304",
    "pid": "23",
    "name": "晋中",
    "ad_name": "晋中市",
    "letter": "jinzhong"
  }, {
    "id": "305",
    "pid": "23",
    "name": "临汾",
    "ad_name": "临汾市",
    "letter": "linfen"
  }, {
    "id": "306",
    "pid": "23",
    "name": "吕梁",
    "ad_name": "吕梁市",
    "letter": "lvliang"
  }, {
    "id": "307",
    "pid": "23",
    "name": "朔州",
    "ad_name": "朔州市",
    "letter": "shuozhou"
  }, {
    "id": "308",
    "pid": "23",
    "name": "忻州",
    "ad_name": "忻州市",
    "letter": "xinzhou"
  }, {
    "id": "309",
    "pid": "23",
    "name": "阳泉",
    "ad_name": "阳泉市",
    "letter": "yangquan"
  }, {
    "id": "310",
    "pid": "23",
    "name": "运城",
    "ad_name": "运城市",
    "letter": "yuncheng"
  }]
}, {
  "id": "24",
  "pid": "1",
  "name": "陕西",
  "ad_name": "陕西省",
  "letter": "sx",
  "has_children": 1,
  "children": [{
    "id": "24",
    "pid": "1",
    "name": "陕西",
    "ad_name": "陕西省",
    "letter": "sx"
  }, {
    "id": "311",
    "pid": "24",
    "name": "西安",
    "ad_name": "西安市",
    "letter": "xian"
  }, {
    "id": "312",
    "pid": "24",
    "name": "安康",
    "ad_name": "安康市",
    "letter": "ankang"
  }, {
    "id": "313",
    "pid": "24",
    "name": "宝鸡",
    "ad_name": "宝鸡市",
    "letter": "baoji"
  }, {
    "id": "314",
    "pid": "24",
    "name": "汉中",
    "ad_name": "汉中市",
    "letter": "hanzhong"
  }, {
    "id": "315",
    "pid": "24",
    "name": "商洛",
    "ad_name": "商洛市",
    "letter": "shangluo"
  }, {
    "id": "316",
    "pid": "24",
    "name": "铜川",
    "ad_name": "铜川市",
    "letter": "tongchuan"
  }, {
    "id": "317",
    "pid": "24",
    "name": "渭南",
    "ad_name": "渭南市",
    "letter": "weinan"
  }, {
    "id": "318",
    "pid": "24",
    "name": "咸阳",
    "ad_name": "咸阳市",
    "letter": "xianyang"
  }, {
    "id": "319",
    "pid": "24",
    "name": "延安",
    "ad_name": "延安市",
    "letter": "yanan"
  }, {
    "id": "320",
    "pid": "24",
    "name": "榆林",
    "ad_name": "榆林市",
    "letter": "shanxiyulin"
  }]
}, {
  "id": "25",
  "pid": "1",
  "name": "上海",
  "ad_name": "上海市",
  "letter": "shanghai",
  "has_children": 0,
  "children": []
}, {
  "id": "26",
  "pid": "1",
  "name": "四川",
  "ad_name": "四川省",
  "letter": "sichuan",
  "has_children": 1,
  "children": [{
    "id": "26",
    "pid": "1",
    "name": "四川",
    "ad_name": "四川省",
    "letter": "sichuan"
  }, {
    "id": "322",
    "pid": "26",
    "name": "成都",
    "ad_name": "成都市",
    "letter": "chengdu"
  }, {
    "id": "323",
    "pid": "26",
    "name": "绵阳",
    "ad_name": "绵阳市",
    "letter": "mianyang"
  }, {
    "id": "324",
    "pid": "26",
    "name": "阿坝",
    "ad_name": "阿坝藏族羌族自治州",
    "letter": "aba"
  }, {
    "id": "325",
    "pid": "26",
    "name": "巴中",
    "ad_name": "巴中市",
    "letter": "bazhong"
  }, {
    "id": "326",
    "pid": "26",
    "name": "达州",
    "ad_name": "达州市",
    "letter": "dazhou"
  }, {
    "id": "327",
    "pid": "26",
    "name": "德阳",
    "ad_name": "德阳市",
    "letter": "deyang"
  }, {
    "id": "328",
    "pid": "26",
    "name": "甘孜",
    "ad_name": "甘孜藏族自治州",
    "letter": "ganzi"
  }, {
    "id": "329",
    "pid": "26",
    "name": "广安",
    "ad_name": "广安市",
    "letter": "guangan"
  }, {
    "id": "330",
    "pid": "26",
    "name": "广元",
    "ad_name": "广元市",
    "letter": "guangyuan"
  }, {
    "id": "331",
    "pid": "26",
    "name": "乐山",
    "ad_name": "乐山市",
    "letter": "leshan"
  }, {
    "id": "332",
    "pid": "26",
    "name": "凉山",
    "ad_name": "凉山彝族自治州",
    "letter": "liangshan"
  }, {
    "id": "333",
    "pid": "26",
    "name": "眉山",
    "ad_name": "眉山市",
    "letter": "meishan"
  }, {
    "id": "334",
    "pid": "26",
    "name": "南充",
    "ad_name": "南充市",
    "letter": "nanchong"
  }, {
    "id": "335",
    "pid": "26",
    "name": "内江",
    "ad_name": "内江市",
    "letter": "neijiang"
  }, {
    "id": "336",
    "pid": "26",
    "name": "攀枝花",
    "ad_name": "攀枝花市",
    "letter": "panzhihua"
  }, {
    "id": "337",
    "pid": "26",
    "name": "遂宁",
    "ad_name": "遂宁市",
    "letter": "suining"
  }, {
    "id": "338",
    "pid": "26",
    "name": "雅安",
    "ad_name": "雅安市",
    "letter": "yaan"
  }, {
    "id": "339",
    "pid": "26",
    "name": "宜宾",
    "ad_name": "宜宾市",
    "letter": "yibin"
  }, {
    "id": "340",
    "pid": "26",
    "name": "资阳",
    "ad_name": "资阳市",
    "letter": "ziyang"
  }, {
    "id": "341",
    "pid": "26",
    "name": "自贡",
    "ad_name": "自贡市",
    "letter": "zigong"
  }, {
    "id": "342",
    "pid": "26",
    "name": "泸州",
    "ad_name": "泸州市",
    "letter": "luzhou"
  }]
}, {
  "id": "27",
  "pid": "1",
  "name": "天津",
  "ad_name": "天津市",
  "letter": "tianjin",
  "has_children": 0,
  "children": []
}, {
  "id": "28",
  "pid": "1",
  "name": "西藏",
  "ad_name": "西藏自治区",
  "letter": "xizang",
  "has_children": 1,
  "children": [{
    "id": "28",
    "pid": "1",
    "name": "西藏",
    "ad_name": "西藏自治区",
    "letter": "xizang"
  }, {
    "id": "344",
    "pid": "28",
    "name": "拉萨",
    "ad_name": "拉萨市",
    "letter": "lasa"
  }, {
    "id": "345",
    "pid": "28",
    "name": "阿里",
    "ad_name": "阿里地区",
    "letter": "ali"
  }, {
    "id": "346",
    "pid": "28",
    "name": "昌都",
    "ad_name": "昌都市",
    "letter": "changdu"
  }, {
    "id": "347",
    "pid": "28",
    "name": "林芝",
    "ad_name": "林芝市",
    "letter": "linzhi"
  }, {
    "id": "348",
    "pid": "28",
    "name": "那曲",
    "ad_name": "那曲市",
    "letter": "naqu"
  }, {
    "id": "349",
    "pid": "28",
    "name": "日喀则",
    "ad_name": "日喀则市",
    "letter": "rikeze"
  }, {
    "id": "350",
    "pid": "28",
    "name": "山南",
    "ad_name": "山南市",
    "letter": "shannan"
  }]
}, {
  "id": "29",
  "pid": "1",
  "name": "新疆",
  "ad_name": "新疆维吾尔自治区",
  "letter": "xinjiang",
  "has_children": 1,
  "children": [{
    "id": "29",
    "pid": "1",
    "name": "新疆",
    "ad_name": "新疆维吾尔自治区",
    "letter": "xinjiang"
  }, {
    "id": "351",
    "pid": "29",
    "name": "乌鲁木齐",
    "ad_name": "乌鲁木齐市",
    "letter": "wulumuqi"
  }, {
    "id": "352",
    "pid": "29",
    "name": "阿克苏",
    "ad_name": "阿克苏地区",
    "letter": "akesu"
  }, {
    "id": "353",
    "pid": "29",
    "name": "阿拉尔",
    "ad_name": "阿拉尔市",
    "letter": "alaer"
  }, {
    "id": "354",
    "pid": "29",
    "name": "巴音郭楞",
    "ad_name": "巴音郭楞蒙古自治州",
    "letter": "bayingeleng"
  }, {
    "id": "355",
    "pid": "29",
    "name": "博尔塔拉",
    "ad_name": "博尔塔拉蒙古自治州",
    "letter": "boerdala"
  }, {
    "id": "356",
    "pid": "29",
    "name": "昌吉",
    "ad_name": "昌吉回族自治州",
    "letter": "changji"
  }, {
    "id": "357",
    "pid": "29",
    "name": "哈密",
    "ad_name": "哈密市",
    "letter": "hami"
  }, {
    "id": "358",
    "pid": "29",
    "name": "和田",
    "ad_name": "和田地区",
    "letter": "hetian"
  }, {
    "id": "359",
    "pid": "29",
    "name": "喀什",
    "ad_name": "喀什地区",
    "letter": "kashi"
  }, {
    "id": "360",
    "pid": "29",
    "name": "克拉玛依",
    "ad_name": "克拉玛依市",
    "letter": "kalamayi"
  }, {
    "id": "361",
    "pid": "29",
    "name": "克孜勒苏",
    "ad_name": "克孜勒苏柯尔克孜自治州",
    "letter": "kezilesu"
  }, {
    "id": "362",
    "pid": "29",
    "name": "石河子",
    "ad_name": "石河子市",
    "letter": "shihezi"
  }, {
    "id": "363",
    "pid": "29",
    "name": "图木舒克",
    "ad_name": "图木舒克市",
    "letter": "tumushuke"
  }, {
    "id": "364",
    "pid": "29",
    "name": "吐鲁番",
    "ad_name": "吐鲁番市",
    "letter": "tulufan"
  }, {
    "id": "365",
    "pid": "29",
    "name": "五家渠",
    "ad_name": "五家渠市",
    "letter": "wujiaqu"
  }, {
    "id": "366",
    "pid": "29",
    "name": "伊犁",
    "ad_name": "伊犁哈萨克自治州",
    "letter": "yili"
  }, {
    "id": "6156",
    "pid": "29",
    "name": "塔城地区",
    "ad_name": "塔城地区",
    "letter": "tachengdiqu"
  }, {
    "id": "6157",
    "pid": "29",
    "name": "阿勒泰地区",
    "ad_name": "阿勒泰地区",
    "letter": "aertai"
  }]
}, {
  "id": "30",
  "pid": "1",
  "name": "云南",
  "ad_name": "云南省",
  "letter": "yunnan",
  "has_children": 1,
  "children": [{
    "id": "30",
    "pid": "1",
    "name": "云南",
    "ad_name": "云南省",
    "letter": "yunnan"
  }, {
    "id": "367",
    "pid": "30",
    "name": "昆明",
    "ad_name": "昆明市",
    "letter": "kunming"
  }, {
    "id": "368",
    "pid": "30",
    "name": "怒江",
    "ad_name": "怒江",
    "letter": "nujiang"
  }, {
    "id": "369",
    "pid": "30",
    "name": "普洱",
    "ad_name": "普洱市",
    "letter": "puer"
  }, {
    "id": "370",
    "pid": "30",
    "name": "丽江",
    "ad_name": "丽江市",
    "letter": "lijiang"
  }, {
    "id": "371",
    "pid": "30",
    "name": "保山",
    "ad_name": "保山市",
    "letter": "baoshan"
  }, {
    "id": "372",
    "pid": "30",
    "name": "楚雄",
    "ad_name": "楚雄彝族自治州",
    "letter": "chuxiong"
  }, {
    "id": "373",
    "pid": "30",
    "name": "大理",
    "ad_name": "大理白族自治州",
    "letter": "dali"
  }, {
    "id": "374",
    "pid": "30",
    "name": "德宏",
    "ad_name": "德宏傣族景颇族自治州",
    "letter": "dehong"
  }, {
    "id": "375",
    "pid": "30",
    "name": "迪庆",
    "ad_name": "迪庆藏族自治州",
    "letter": "diqing"
  }, {
    "id": "376",
    "pid": "30",
    "name": "红河",
    "ad_name": "红河哈尼族彝族自治州",
    "letter": "honghe"
  }, {
    "id": "377",
    "pid": "30",
    "name": "临沧",
    "ad_name": "临沧市",
    "letter": "lincang"
  }, {
    "id": "378",
    "pid": "30",
    "name": "曲靖",
    "ad_name": "曲靖市",
    "letter": "qujing"
  }, {
    "id": "379",
    "pid": "30",
    "name": "文山",
    "ad_name": "文山壮族苗族自治州",
    "letter": "wenshan"
  }, {
    "id": "380",
    "pid": "30",
    "name": "西双版纳",
    "ad_name": "西双版纳傣族自治州",
    "letter": "xishuangbanna"
  }, {
    "id": "381",
    "pid": "30",
    "name": "玉溪",
    "ad_name": "玉溪市",
    "letter": "yuxi"
  }, {
    "id": "382",
    "pid": "30",
    "name": "昭通",
    "ad_name": "昭通市",
    "letter": "zhaotong"
  }]
}, {
  "id": "31",
  "pid": "1",
  "name": "浙江",
  "ad_name": "浙江省",
  "letter": "zhejiang",
  "has_children": 1,
  "children": [{
    "id": "31",
    "pid": "1",
    "name": "浙江",
    "ad_name": "浙江省",
    "letter": "zhejiang"
  }, {
    "id": "383",
    "pid": "31",
    "name": "杭州",
    "ad_name": "杭州市",
    "letter": "hangzhou"
  }, {
    "id": "384",
    "pid": "31",
    "name": "湖州",
    "ad_name": "湖州市",
    "letter": "huzhou"
  }, {
    "id": "385",
    "pid": "31",
    "name": "嘉兴",
    "ad_name": "嘉兴市",
    "letter": "jiaxing"
  }, {
    "id": "386",
    "pid": "31",
    "name": "金华",
    "ad_name": "金华市",
    "letter": "jinhua"
  }, {
    "id": "387",
    "pid": "31",
    "name": "丽水",
    "ad_name": "丽水市",
    "letter": "lishui"
  }, {
    "id": "388",
    "pid": "31",
    "name": "宁波",
    "ad_name": "宁波市",
    "letter": "ningbo"
  }, {
    "id": "389",
    "pid": "31",
    "name": "绍兴",
    "ad_name": "绍兴市",
    "letter": "shaoxing"
  }, {
    "id": "390",
    "pid": "31",
    "name": "台州",
    "ad_name": "台州市",
    "letter": "zhejiangtaizhou"
  }, {
    "id": "391",
    "pid": "31",
    "name": "温州",
    "ad_name": "温州市",
    "letter": "wenzhou"
  }, {
    "id": "392",
    "pid": "31",
    "name": "舟山",
    "ad_name": "舟山市",
    "letter": "zhoushan"
  }, {
    "id": "393",
    "pid": "31",
    "name": "衢州",
    "ad_name": "衢州市",
    "letter": "quzhou"
  }]
}, {
  "id": "32",
  "pid": "1",
  "name": "重庆",
  "ad_name": "重庆市",
  "letter": "chongqing",
  "has_children": 0,
  "children": []
}]

export interface SimpleChildItems {
  id: string,
  name: string
}

export interface ChildItems extends SimpleChildItems {
  pid: string,
  ad_name: string,
  letter: string
}

export interface ParentItems {
  id: string,
  pid: string,
  name: string,
  ad_name: string,
  letter: string,
  has_children: number,
  children: ChildItems[],
}

// 用户定位返回信息
export interface UserLocationPromiss {
  province: string,
  city: string,
  adcode: string,
  citycode: string
}

// * 默认全国数据
export const AREACHINA: ParentItems = AREAS[0]
// * 默认北京数据
export const AREABEIJING: ParentItems = AREAS[1]
// * 定位返回省份信息 0返回省份 1返回城市 
export function getCityInfo(data: UserLocationPromiss, current = 0): ChildItems{
  let len: number = AREAS.length
  let flag: boolean = false
  if(!current){
    let items: ParentItems[] = AREAS.filter(item => data.province.indexOf(item.name) !== -1)
    if (items.length) {
      return items[0]
    } else{
      //根据城市名称查找
      for(let i:number = 0;i < len; i++){
        let item = AREAS[i]
        if (item.has_children) {
          let itemArea: ChildItems[] = item.children
          let dlen: number = itemArea.length
          for(let k: number = 0; k < dlen; k++){
            let d: ChildItems = itemArea[k]
            if (data.city.indexOf(d.name) !== -1) {
              let province: ChildItems = {
                id: item.id,
                pid: item.pid,
                ad_name: item.ad_name,
                name: item.name,
                letter: item.letter
              }
              flag = true
              return province
              break
            }
          }
          if(flag) break
        }
      }
    }
  }else{
    let items: ParentItems[] = AREAS.filter(item => data.city.indexOf(item.name) !== -1)
    if(items.length) return items[0]
    for(let i: number = 0; i < len; i++){
      let item = AREAS[i]
      if (item.has_children) {
        let itemArea: ChildItems[] = item.children
        let dlen: number = itemArea.length
        for(let k: number = 0; k < dlen; k++){
          let d: ChildItems = itemArea[k]
          if (data.city.indexOf(d.name) !== -1) {
            flag = true
            return d
            break
          }
        }
        if (flag) break
      }
    }
  }
  // 查询不到内容 直接返回全国/北京
  return current ? AREABEIJING : AREACHINA
}
// 根据城市名字返回数据内名字
export function getLongAreaAdname(title: string): string {
  let area: string = '北京市'
  if(!title) return area
  let flag: boolean = false
  for (let i: number = 1, len: number = AREAS.length -1; i< len; i ++){
    if(flag) break
    if(title.indexOf(AREAS[i].name) !== -1){
      return AREAS[i].ad_name
      break
    }
    if (AREAS[i].has_children){
      let ChildItems = AREAS[i].children
      for(let j: number = 0, clen: number = 0; j < clen; j++){
        if (title.indexOf(ChildItems[j].name) !== -1){
          flag = true
          return ChildItems[j].ad_name
          break
        }
      }
    }
    
  }
  return area
}

// 根据城市id返回城市信息
export function getCityInfoById(id: string){
  let pCurrent = 0
  let cCurrent = 0 //默认返回该下标的数据
  let flag = false // 是否已经找到了数据
  let index: number = AREAS.findIndex(item => item.id == id)
  if(index > -1){
    return AREAS[index]
  }
  for(let i = 0 ;i < AREAS.length; i++){
    if (AREAS[i].has_children){
      let items = AREAS[i].children
      for(let j = 0; j < items.length; j++){
        let item = items[j]
        if(item.id == id){
          pCurrent = i
          cCurrent = j
          flag = true
          break
        }
      }
    }
    if(flag) break
  }
  if (flag) return AREAS[pCurrent].children[cCurrent]
  return AREAS[pCurrent]
}

// 省市选择picker 非高德地图场景最多
export function getCityAreaPicker(){
  let province: SimpleChildItems[] = []
  let cities: SimpleChildItems[][] = []
  for (let i = 1; i < AREAS.length; i ++){
    let data = AREAS[i]
    province.push({ id: data.id, name: data.name })
    if (data.has_children){
      let mydata: SimpleChildItems[] = []
      let childrenData = data.children
      for (let j = 1; j < childrenData.length;j ++){
        mydata.push({ id: childrenData[j].id, name: childrenData[j].name })
      }
      cities.push(mydata)
    }else{
      cities.push([{ id: data.id, name: data.name }])
    }
  }
  // 先将数据进行浅拷贝，避免没注意的情况改变了数据
  province = [...province]
  cities = [...cities]
  return {
    province,
    cities
  }
}

// 根据省市返回下标 如[2,5] 非高德地图经常会调用picker 这个时候使用场景最多
export function getAreaCurrentArr(pid: string,cid: string): {pi: number, ci: number}{
  let { province, cities } = getCityAreaPicker()
  // 先获取父级的索引，然后通过父级索引直接定位到子集索引
  let pi: number = province.findIndex(item => item.id == pid)
  let citydata = JSON.parse(JSON.stringify(cities[pi]))
  let ci: number = citydata.findIndex(item => item.id == cid)
  return {pi ,ci}
}


export default AREAS